spring:
  application:
    name: eureka-server
    
server:
  port: 2001
  
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
    register-with-eureka: false
    fetch-registry: false
    
  
